# Generated by Django 6.0.2 on 2026-03-12 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_payment_created_at_payment_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
