# Generated by Django 6.0.2 on 2026-03-12 10:14

import uuid
from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    Certificate = apps.get_model("reports", "Certificate")
    for row in Certificate.objects.all():
        row.certificate_id = uuid.uuid4()
        row.save(update_fields=["certificate_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        # Step 1: add field nullable, no unique constraint yet
        migrations.AddField(
            model_name='certificate',
            name='certificate_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        # Step 2: populate unique UUIDs for any existing rows
        migrations.RunPython(gen_uuid, migrations.RunPython.noop),
        # Step 3: enforce unique + non-null
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
